# Generated by Django 2.2.5 on 2019-09-19 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality_name', models.CharField(choices=[('US', 'Ultrasound'), ('CR', 'X-ray'), ('NM', 'Bone Densitometry'), ('MG', 'Mammography')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TechNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('exam_date', models.DateField()),
                ('tech_initials', models.CharField(max_length=10)),
                ('patient_age', models.CharField(max_length=4)),
                ('accession', models.CharField(max_length=10)),
                ('comments', models.TextField()),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_forms.Modality')),
            ],
        ),
    ]
