# Generated by Django 2.2.5 on 2019-09-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modality',
            name='modality_name',
            field=models.CharField(max_length=20),
        ),
    ]
