# Generated by Django 2.2.5 on 2019-09-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_forms', '0002_auto_20190919_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technote',
            name='modality',
        ),
        migrations.DeleteModel(
            name='Modality',
        ),
        migrations.DeleteModel(
            name='TechNote',
        ),
    ]
