# Generated by Django 2.2.5 on 2019-09-26 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationConfigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_ae', models.CharField(max_length=20)),
                ('destination_ip', models.CharField(max_length=30)),
                ('destination_port', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
            ],
        ),
        migrations.CreateModel(
            name='WorklistConfigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worklist_ae', models.CharField(max_length=20)),
                ('worklist_ip', models.CharField(max_length=30)),
                ('worklist_port', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
            ],
        ),
    ]
