# Generated by Django 2.2.5 on 2019-09-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkstationConfigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstation_ae', models.CharField(max_length=30)),
            ],
        ),
    ]
