# Generated by Django 2.2.5 on 2019-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_configs', '0002_workstationconfigs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIDvalues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(max_length=60)),
                ('series_instance_uid', models.CharField(max_length=60)),
                ('sop_instance_uid', models.CharField(max_length=60)),
                ('implementation_class_uid', models.CharField(max_length=60)),
            ],
        ),
    ]
